### ISSUE TITLE
Where to configure cassandra hosts and credentials to run ndbench

### ISSUE THREAD

**Issue by chanakyaclip** [Netflix/ndbench#74]
Hi,

I tried a lot over the web to find a good getting started tutorial for ndbench to benchmark Cassandra but failed to find one. None of the posts available online walks us through testing cassandra in cloud environment. If you guys can guide me to any information on it, that would be of a great help.

If there is any configuration file which I need to use to give cluster details with credentials please point me to it.

Thanks in advance.

**Comment by vinaykumarchella** [comment]
Sure. You can put C* related configuration in any of the NdBench configuration files. For e.g., - You can start putting them https://github.com/Netflix/ndbench/blob/master/ndbench-core/src/main/resources/application.properties. C* cluster name, IP address and port can be configured using NDBench C* plugin configurations, you can find more information on this @ our wiki - https://github.com/Netflix/ndbench/tree/master/ndbench-cass-plugins. 

P.S: You can find us on gitter @ https://gitter.im/Netflix/ndbench for quicker response to such questions instead of opening an issue.
